### PR TITLE
Travis CI: Turn on tests

### PR DESCRIPTION
**Pull request by cclauss**

### CODE REVIEW

**Comment by oaubert** [comment]
For the tests to succeed, you need to have a working install of libvlc. So you should add a "apt-get install libvlc5 libvlc-dev" to the travis config file.

**Comment by cclauss** [comment]
https://travis-ci.org/oaubert/python-vlc/jobs/403569440#L920 sayz Setting up vlc (2.1.6-0ubuntu14.04.4) ...

**Comment by cclauss** [comment]
I don't seem to be making progress...
* Python 2: __make__ seems happy but then __import vlc__ fails and __make test_ on a NameError.
* Python 3: __make__ seems to fail.

**Comment by oaubert** [comment]
The current head in git expects to build for vlc 3.*. In the travis Trusty environment, this version of VLC is not readily available. A solution could be to move to a Docker-based environment to more easily get the appropriate vlc version.

**Comment by cclauss** [comment]
Upgrading from Ubuntu Trusty to Xenial seems to help Python 3 but we still get VLC version 2.2.2 Weatherwax.

Is there a way to get __make__ to generate 2.2 bindings?  Or would that be useless for our purposes?

**Comment by oaubert** [comment]
It is useless and error-prone: the generator has been adapted to work on recent releases only. The generated/2.2 is kept in the repo for archive purposes only, and is not supposed to evolve.

**Comment by cclauss** [comment]
OK...  We now have __VLC media player 3.0.3 Vetinari (revision 3.0.3-1-3-gf09fd0d)__ loading.

**Comment by cclauss** [comment]
How can we make progress?  https://travis-ci.org/oaubert/python-vlc

**Comment by oaubert** [comment]
There are 2 different steps here:

- the repository contains a version of the generated module (in generated/3.0). It can be tested with `make tests`, if a vlc binary is installed and findable. It does not require libvlc-dev.

- the module could be generated in travis, which would then require the presence of the libvlc include files (from libvlc-dev). This is really optional, since I currently do the generation/tests/distribution on my computer, but it would improve the reproducibility in the end.

I would focus in a first step on getting `make tests` running. The command `python -c "import sys, vlc ; print(sys.version, vlc.__version__, vlc.__libvlc_version__)"` should be prefixed with `PYTHONPATH=generated/3.0` 

For the `core libvlc error: No plugins found! Check your VLC installation.`, it means that libvlc-core is loaded but it has trouble finding the plugins. Maybe try to run `vlc --verbose 3 --version` to get information about the plugins directory, then specify it through the PLUGIN_PATH env. var.

**Comment by cclauss** [comment]
Suggestions?

**Pull request closed without merging**
