### PR TITLE
Add automated testing via Travis CI and flake8

### PR DESCRIPTION
**Pull request by cclauss**
Travis CI can be used to do automated testing on all pull requests before they are reviewed and merged. This service is free to open source projects like this one. For this to work, @oaubert would need to turn on the repo switch for this repo at https://www.travis-ci.org/oaubert/python-vlc (login via GitHub credentials)

### CODE REVIEW

**Comment by oaubert** [comment]
Hi @cclauss 
Thanks for the suggestion and the patches. It is a good opportunity to improve the python-vlc codebase. I see that you contributed some patches to the code in this pull request to fix the flake8-reported errors/warnings. Let me know when your pull request is considered final, so that I can merge your changes.

**Comment by cclauss** [comment]
Final.

**Comment by cclauss** [comment]
Thanks.  It would be good to get this one checked in.

**Comment by cclauss** [comment]
Ready for your review.

**Pull request merged**
